config/routes.rb
Rails.application.routes.draw do
  
  root "welcome#home"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  post '/logout', to: "sessions#destroy"
  get '/signup', to: "hosts#new"
  get '/auth/:provider/callback', to: 'sessions#create'

  resources :hosts do
    resources :shows do
      resources :interviews
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/interviews_controller.rb
# Copyright 2019, Ryan Sise

# This file is part of Podcast Interview Manager.

# Podcast Interview Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Podcast Interview Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Podcast Interview Manager.  If not, see <https://www.gnu.org/licenses/>.

class InterviewsController < ApplicationController

  def new
    if logged_in?
      grab_host_show
      @interview = Interview.new
      @guest = Guest.new
    else
      redirect_to root_path
    end
  end

  def create
    if logged_in?
      grab_host_show
      @interview = @show.interviews.new(interview_params)
      @guest = @interview.build_guest(interview_params[:guest_attributes])
      if @guest.save
        @interview.guest = @guest
        if @interview.save
          @show.interviews << @interview
          if @show.save
            redirect_to host_show_path(@host, @show)
          else
            render 'interviews/new'
          end
        else
          render 'interviews/new'
        end
      else
        render 'interviews/new'
      end
    else
      redirect_to root_path
    end
  end

  def show
    if logged_in?
      grab_host_show_int
    else
      redirect_to root_path
    end
  end

  def update
    grab_host_show_int
    @interview.update_attributes(interview_params)
    redirect_to host_show_path(@host, @show)
  end

  def destroy
    if logged_in?
      grab_host_show_int
      @interview.destroy
      redirect_to host_show_path(@host, @show)
    else
      redirect_to root_path
    end
  end

  private
  def interview_params
    params.require(:interview).permit(:date, :start_time, :end_time, :recorded, :published, guest_attributes:[:name, :email, :expertise])
  end

  def grab_host_show
    @host = Host.find(session[:host_id])
    @show = Show.find(params[:show_id])
  end

  def grab_host_show_int
    @host = Host.find(session[:host_id])
    @show = Show.find(params[:show_id])
    @interview = Interview.find(params[:id])
  end
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/views/interviews/_int-info.html.erb
<%# Copyright 2019, Ryan Sise

This file is part of Podcast Interview Manager.

Podcast Interview Manager is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Podcast Interview Manager is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Podcast Interview Manager.  If not, see <https://www.gnu.org/licenses/>. %>

<%=@interview.date%><br>
<%=@interview.start_time%> - <%=@interview.end_time%><br>
================<br>
<%=@interview.guest.name%><br>
<%=@interview.guest.email%><br>
<%=@interview.guest.expertise%><br>

<%=form_for @interview, :url => {:action => "update"} do |form|%>
  <%=form.label :recorded%>
  <%=form.check_box :recorded%><br>
  <%=form.label :published%>
  <%=form.check_box :published%><br>
  <%=form.submit%>
<%end%>

app/views/interviews/_new-int.html.erb
<%# Copyright 2019, Ryan Sise

This file is part of Podcast Interview Manager.

Podcast Interview Manager is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Podcast Interview Manager is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Podcast Interview Manager.  If not, see <https://www.gnu.org/licenses/>. %>

<%=form_for(@interview, url: host_show_interviews_path) do |form|%>
  <% if @interview.errors.any? %>
    <div id="error_explanation">
      <h4>There were some errors:</h4>
      <ul>
        <% @interview.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  Interview Data:<br>
  <br>
  <%=form.label :date%>(mm/dd/yyyy)<br>
  <%=form.text_field :date%><br>
  <br>
  <%=form.label :start_time%><br>
  <%=form.text_field :start_time%><br>
  <br>
  <%=form.label :end_time%><br>
  <%=form.text_field :end_time%><br>
  <%=form.fields_for :guest, @interview.build_guest do |guest_form|%>
    <% if @guest.errors.any? %>
    <div id="error_explanation">
      <h4>There were some errors:</h4>
      <ul>
        <% @guest.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <br>
    Guest Data:<br>
    <br>
    <%=guest_form.label :name%><br>
    <%=guest_form.text_field :name%><br>
    <br>
    <%=guest_form.label :email%><br>
    <%=guest_form.text_field :email%><br>
    <br>
    <%=guest_form.label :expertise%><br>
    <%=guest_form.text_field :expertise%><br>
    <br>
  <%end%>
  <%=form.submit%>
<%end%>

app/views/interviews/new.html.erb
<%# Copyright 2019, Ryan Sise

This file is part of Podcast Interview Manager.

Podcast Interview Manager is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Podcast Interview Manager is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Podcast Interview Manager.  If not, see <https://www.gnu.org/licenses/>. %>

<h1>Create Interview for <%="#{@show.title}"%></h1><br>
<br>
<br>
<%=link_to 'Return Home', host_path(@host)%>
<br>
<br>
<%=link_to "Back to #{@show.title}", host_show_path(@host, @show)%>
<br>
<br>
<%=render 'new-int'%>

app/views/interviews/show.html.erb
<%# Copyright 2019, Ryan Sise

This file is part of Podcast Interview Manager.

Podcast Interview Manager is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Podcast Interview Manager is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Podcast Interview Manager.  If not, see <https://www.gnu.org/licenses/>. %>

<h1>Interview for <%="#{@show.title}"%></h1><br>
<br>
<%=link_to 'Return Home', host_path(@host)%><br>
<br>
<%=render 'int-info'%>
<br>
<br>
<%=link_to 'Delete Interview', host_show_interview_path(@host, @show, @interview), :data => {confirm: 'Are you sure?'}, :method => :delete%>