config/routes.rb
Rails.application.routes.draw do
  
  root "welcome#home"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  post '/logout', to: "sessions#destroy"
  get '/signup', to: "hosts#new"
  get '/auth/:provider/callback', to: 'sessions#create'

  resources :hosts do
    resources :shows do
      resources :interviews
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/host.rb
# Copyright 2019, Ryan Sise

# This file is part of Podcast Interview Manager.

# Podcast Interview Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Podcast Interview Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Podcast Interview Manager.  If not, see <https://www.gnu.org/licenses/>.

class Host < ApplicationRecord
  has_secure_password
  has_many :shows
  has_many :interviews, through: :shows
  validates :name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
  
end

app/controllers/hosts_controller.rb
# Copyright 2019, Ryan Sise

# This file is part of Podcast Interview Manager.

# Podcast Interview Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Podcast Interview Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Podcast Interview Manager.  If not, see <https://www.gnu.org/licenses/>.

class HostsController < ApplicationController

  def new
    @host = Host.new
  end

  def create
    @host = Host.new(host_params)
    if @host.save
      redirect_to '/login'
    else
      render 'hosts/new'
    end
  end

  def show
    if logged_in?
      grab_host
      @shows = @host.shows
    else
      redirect_to root_path
    end
  end

  def destroy
    grab_host
    @host.destroy
    redirect_to root_path
  end

  private
  def host_params
    params.require(:host).permit(:name, :email, :password)
  end

  def grab_host
    @host = Host.find(session[:host_id])
  end
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/views/hosts/_login-form.html.erb
<%# Copyright 2019, Ryan Sise

This file is part of Podcast Interview Manager.

Podcast Interview Manager is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Podcast Interview Manager is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Podcast Interview Manager.  If not, see <https://www.gnu.org/licenses/>. %>

<%if flash[:notice]%>
  <h2><%=flash[:title]%></h2>
  <h3><%=flash[:notice]%></h3>
<%end%>
<%=form_tag('/login') do%>
  <%=label_tag('host[email]', "Email")%><br>
  <%=text_field_tag('host[email]')%><br>
  <br>
  <%=label_tag('host[password]', "Password")%><br>
  <%=password_field_tag('host[password]')%><br>
  <br>
  <%=submit_tag('Login')%>
<%end%>

app/views/hosts/_new-host.html.erb
<%# Copyright 2019, Ryan Sise

This file is part of Podcast Interview Manager.

Podcast Interview Manager is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Podcast Interview Manager is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Podcast Interview Manager.  If not, see <https://www.gnu.org/licenses/>. %>

<%=form_for @host do |form|%>
  <% if @host.errors.any? %>
    <div id="error_explanation">
      <h4>There were some errors:</h4>
      <ul>
        <% @host.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%=form.label :name%><br>
  <%=form.text_field :name%><br>
  <%=form.label :email%><br>
  <%=form.text_field :email%><br>
  <%=form.label :password%><br>
  <%=form.password_field :password%><br>
  <%=form.submit%>
<%end%>

app/views/hosts/login.html.erb
<%# Copyright 2019, Ryan Sise

This file is part of Podcast Interview Manager.

Podcast Interview Manager is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Podcast Interview Manager is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Podcast Interview Manager.  If not, see <https://www.gnu.org/licenses/>. %>

<h1>Login</h1>
<br>
<br>
<%=link_to 'Back to Front Page', '/'%><br>
<br>
<%=render 'hosts/login-form'%>

app/views/hosts/new.html.erb
<%# Copyright 2019, Ryan Sise

This file is part of Podcast Interview Manager.

Podcast Interview Manager is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Podcast Interview Manager is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Podcast Interview Manager.  If not, see <https://www.gnu.org/licenses/>. %>

<h2>New Host Form</h2>
<br>
<%=link_to 'Back to Front Page', '/'%><br>
<br>
<%=render 'new-host'%>

app/views/hosts/show.html.erb
<%# Copyright 2019, Ryan Sise

This file is part of Podcast Interview Manager.

Podcast Interview Manager is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Podcast Interview Manager is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Podcast Interview Manager.  If not, see <https://www.gnu.org/licenses/>. %>

<h1>Your Homepage</h1>
<br>
<br>
<%=@host.name%><br>
<%=@host.email%><br>
<br>
<br>
<h2>Your Podcasts!</h2>
<ul>
  <%@shows.each do |podcast|%>
    <li><%=link_to podcast.title, host_show_path(podcast.host_id, podcast.id)%></li>
  <%end%>
</ul>
<br>
<%=button_to 'Create New Show', new_host_show_path(@host), method: 'get'%><br>
<br>
<%=button_to 'Logout', logout_path, :method => :post%>
<br>
<br>
<br>
<%=button_to 'Delete My Account', host_path(@host), :data => {confirm: 'Are you sure?'}, :method => :delete%>