config/routes.rb
Rails.application.routes.draw do
  
  root "welcome#home"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  post '/logout', to: "sessions#destroy"
  get '/signup', to: "hosts#new"
  get '/auth/:provider/callback', to: 'sessions#create'

  resources :hosts do
    resources :shows do
      resources :interviews
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/show.rb
# Copyright 2019, Ryan Sise

# This file is part of Podcast Interview Manager.

# Podcast Interview Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Podcast Interview Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Podcast Interview Manager.  If not, see <https://www.gnu.org/licenses/>.

class Show < ApplicationRecord
  has_many :interviews
  has_many :guests, through: :interviews
  validates :title, presence: true
  validates :description, presence: true
  validates :category, presence: true
  validates :url, presence: true
  validates :duration, presence: true
  validates :title, uniqueness: true
  validates :url, uniqueness: true
  
end

app/controllers/shows_controller.rb
# Copyright 2019, Ryan Sise

# This file is part of Podcast Interview Manager.

# Podcast Interview Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Podcast Interview Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Podcast Interview Manager.  If not, see <https://www.gnu.org/licenses/>.

class ShowsController < ApplicationController

  def new
    if logged_in?
      @host = Host.find(session[:host_id])
      @show = Show.new
    else
      redirect_to root_path
    end
  end

  def create
    if logged_in?
      @host = Host.find(session[:host_id])
      @show = Show.new(show_params)
      if @show.save
        @host.shows << @show
        @host.save
        @show.save
        redirect_to host_path(@host)
      else
        render 'shows/new'
      end
    else
      redirect_to root_path
    end
  end

  def edit
    if logged_in?
      @host = Host.find(session[:host_id])
      @show = Show.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def show
    if logged_in?
      @host = Host.find(session[:host_id])
      @show = Show.find(params[:id])
      @interview = Interview.new
      @interviews = @show.interviews
    else
      redirect_to root_path
    end
  end

  def update
    if logged_in?
      @host = Host.find(session[:host_id])
      @show = Show.find(params[:id])
      @show.update_attributes(show_params)
      redirect_to host_path(@host)
    else
      redirect_to root_path
    end
  end

  def destroy
    if logged_in?
      @host = Host.find(session[:host_id])
      @show = Show.find(params[:id])
      @show.destroy
      redirect_to host_path(@host)
    else
      redirect_to root_path
    end
  end

  private
  def show_params
    params.require(:show).permit(:title, :description, :category, :url, :duration)
  end

end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/shows/_edit-form.html.erb
<%# Copyright 2019, Ryan Sise

This file is part of Podcast Interview Manager.

Podcast Interview Manager is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Podcast Interview Manager is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Podcast Interview Manager.  If not, see <https://www.gnu.org/licenses/>. %>

<%=form_for @show, :url => {:action => "update"} do |form|%>
  <br>
  <%=form.label :title%><br>
  <%=form.text_field :title%><br>
  <br>
  <%=form.label :description%><br>
  <%=form.text_area :description, cols:30, rows:10%><br>
  <br>
  <%=form.label :category%><br>
  <%=form.text_field :category%><br>
  <br>
  <%=form.label :url%><br>
  <%=form.text_field :url%><br>
  <br>
  <%=form.label :duration%><br>
  <%=form.text_field :duration%><br>
  <br>
  <%=form.submit%>
<%end%>

app/views/shows/_new-form.html.erb
<%# Copyright 2019, Ryan Sise

This file is part of Podcast Interview Manager.

Podcast Interview Manager is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Podcast Interview Manager is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Podcast Interview Manager.  If not, see <https://www.gnu.org/licenses/>. %>

<%=form_for(@show, url:host_shows_path) do |form|%>
  <% if @show.errors.any? %>
    <div id="error_explanation">
      <h4>There were some errors:</h4>
      <ul>
        <% @show.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%=form.label :title%><br>
  <%=form.text_field :title%><br>
  <%=form.label :description%><br>
  <%=form.text_area :description, cols:30, rows:10%><br>
  <%=form.label :category%><br>
  <%=form.text_field :category%><br>
  <%=form.label :url%><br>
  <%=form.text_field :url%><br>
  <%=form.label :duration%><br>
  <%=form.text_field :duration%><br>
  <%=form.submit%>
<%end%>

app/views/shows/edit.html.erb
<%# Copyright 2019, Ryan Sise

This file is part of Podcast Interview Manager.

Podcast Interview Manager is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Podcast Interview Manager is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Podcast Interview Manager.  If not, see <https://www.gnu.org/licenses/>. %>

<h1>Edit Details for <%="#{@show.title}"%></h1>
<br>
<br>
<%=link_to 'Return Home', host_path(@host)%><br>
<br>
<%=link_to "Back to #{@show.title}", host_show_path(@host, @show)%>

<%=render 'edit-form'%>

app/views/shows/new.html.erb
<%# Copyright 2019, Ryan Sise

This file is part of Podcast Interview Manager.

Podcast Interview Manager is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Podcast Interview Manager is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Podcast Interview Manager.  If not, see <https://www.gnu.org/licenses/>. %>

<h1>Create a New Show!</h1>
<br>
<br>
<%=link_to 'Return Home', host_path(@host)%><br>
<br>
<br>
<%=render 'new-form'%>

app/views/shows/show.html.erb
<%# Copyright 2019, Ryan Sise

This file is part of Podcast Interview Manager.

Podcast Interview Manager is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Podcast Interview Manager is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Podcast Interview Manager.  If not, see <https://www.gnu.org/licenses/>. %>

<h1><%="#{@show.title}"%><br></h1>
<br>
<br>
<%=link_to 'Return Home', host_path(@host)%>
<br>
<br>
<h3>Description:</h3>
<%=@show.description%><br>
<br>
<br>
<h3>Category:</h3>
<%=@show.category%><br>
<br>
<br>
<h3>URL:</h3>
<%=@show.url%><br>
<br>
<br>
<h3>Duration:</h3>
<%=@show.duration%><br>
<br>
<%=button_to 'Edit This Show', edit_host_show_path(@show), method: 'get'%><br>
<br>
<%=button_to 'Delete This Show', host_show_path(@host, @show, @interview), :data => {confirm: 'Are you sure?'}, :method => :delete%>
<br>
<h3>Pending Interviews</h3>
<ul>
  <%@interviews.pending.each do |interview_info|%>
    <li><%=link_to interview_info.date, host_show_interview_path(@host, @show, interview_info)%>--<%=interview_info.guest.name%></li>
  <%end%>
</ul>
<br>
<h3>Recorded Interviews</h3>
<ul>
  <%@interviews.was_recorded.each do |interview_info|%>
    <li><%=link_to interview_info.date, host_show_interview_path(@host, @show, interview_info)%>--<%=interview_info.guest.name%></li>
  <%end%>
</ul>
<br>
<h3>Published Interviews</h3>
<ul>
  <%@interviews.is_published.each do |interview_info|%>
    <li><%=link_to interview_info.date, host_show_interview_path(@host, @show, interview_info)%>--<%=interview_info.guest.name%></li>
  <%end%>
</ul>
<br>
<%=button_to 'Setup Interview', new_host_show_interview_path(@host, @show, @interview), method: 'get'%><br>
<br>